apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "flowsketch.fullname" . }}-queries
  labels:
    {{- include "flowsketch.labels" . | nindent 4 }}
data:
  {{- range $name, $query := .Values.queries }}
  {{ $name }}: |
    {{- $query | nindent 4 }}
  {{- end }}
