{{- if and .Values.agent.enabled .Values.serviceAccounts.agent.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "flowsketch.agentServiceAccountName" . }}
  labels:
    {{- include "flowsketch.labels" . | nindent 4 }}
    app.kubernetes.io/component: agent
  {{- with .Values.serviceAccounts.agent.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: false
{{- end }}
{{- if and .Values.agent.enabled .Values.serviceAccounts.agent.create .Values.gateway.enabled .Values.serviceAccounts.gateway.create }}
---
{{- end }}
{{- if and .Values.gateway.enabled .Values.serviceAccounts.gateway.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "flowsketch.gatewayServiceAccountName" . }}
  labels:
    {{- include "flowsketch.labels" . | nindent 4 }}
    app.kubernetes.io/component: gateway
  {{- with .Values.serviceAccounts.gateway.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: false
{{- end }}
